FROM mysql:latest

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=orderapi

# Expose the port the MySQL server will run on
EXPOSE 3306

# Start MySQL server
CMD ["mysqld"]

